/**
 * ============================================================
 *  TRIZA ENGINE — Knowledge Batch: Nature, Animals & Environment
 * ============================================================
 *
 *  15 hand-written entries covering wildlife, ecosystems, earth
 *  processes and environmental science. Each entry includes
 *  English + Roman Urdu trigger patterns so TRIZA can respond
 *  to multilingual user queries natively.
 *
 *  All responses: 250-400 words, markdown formatted, factually
 *  accurate. No external LLM — pure TypeScript knowledge base.
 * ============================================================
 */

import type { KnowledgeEntry } from './types'

export const NATURE_ENTRIES: KnowledgeEntry[] = [
  // ----------------------------------------------------------
  // 1. HOW DO BIRDS FLY
  // ----------------------------------------------------------
  {
    id: 'how-birds-fly',
    patterns: [/\b(birds fly|how birds fly|bird flight|parinde|parindon ki udaan|udaan|aerodynamics of birds|bird wings|par)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## How Do Birds Fly? The Miracle of Avian Flight

Bird flight is one of nature's most elegant solutions to gravity — a fusion of lightweight anatomy, aerodynamic wings, and powerful muscles. Birds are the only surviving descendants of feathered dinosaurs, and flight shaped nearly every system in their bodies.

### The Four Aerodynamic Forces
- **Lift** — generated by the curved upper surface of the wing (airfoil). Air moves faster over the top, lowering pressure and pushing the bird upward.
- **Thrust** — produced by downward and backward strokes of the wings, powered by massive pectoral muscles.
- **Drag** — air resistance, minimized by the bird's streamlined body.
- **Gravity (weight)** — countered by hollow bones and a lightweight skeleton.

### Wing Shapes and Flight Styles
| Wing Type | Example | Style |
|-----------|---------|-------|
| Elliptical | Sparrow, crow | Quick, maneuverable takeoff |
| High-speed | Falcon, swift | Fast level flight |
| Soaring | Albatross, eagle | Long glides over ocean |
| Hovering | Hummingbird | Rapid wingbeats, stationary flight |

### Migration Marvels
Many species travel astonishing distances. The **Arctic Tern** holds the record — flying from Arctic to Antarctic and back each year, about 70,000 km. Bar-tailed Godwits fly non-stop from Alaska to New Zealand in 11 days, over 12,000 km without resting. Birds navigate using the sun, stars, Earth's magnetic field, landmarks, and even smell.

### Special Adaptations
- **Feathers** — lightweight, repairable, and aerodynamic
- **Furcula (wishbone)** — acts as a spring storing energy each stroke
- **Single ovary** — reduces body weight in females
- **Air sacs** — continuous one-way airflow for high-efficiency breathing

**Why it matters:** Flight lets birds exploit ecological niches across every continent, pollinate plants, disperse seeds, and control insect populations. Studying bird flight inspired human aviation — from Da Vinci's sketches to modern aircraft wings — and remains a living laboratory of efficient, low-energy movement that engineers still try to imitate.`,
  },

  // ----------------------------------------------------------
  // 2. HONEY BEES
  // ----------------------------------------------------------
  {
    id: 'honey-bees',
    patterns: [/\b(honey bee|honey bees|shehad ki makhi|makhi|queen bee|bee colony|shehad|honey production|madhumakhi|shahd)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Honey Bees — The Superorganism of the Hive

A honey bee colony is not just a group of insects — it behaves as a single superorganism, with thousands of individuals coordinating through dance, scent, and vibration. A single hive may contain 40,000–80,000 bees, all daughters of one queen.

### Castes in the Hive
- **Queen** — the only fertile female, lays up to 2,000 eggs per day and can live 3–5 years.
- **Workers** — sterile females who forage, nurse young, build comb, guard the hive, and clean. They live only 6 weeks in summer.
- **Drones** — males whose sole function is to mate with a virgin queen; they die immediately after mating.

### How Honey Is Made
1. Workers collect nectar from flowers using a long proboscis.
2. Nectar is stored in a special 'honey stomach' where enzymes begin breaking complex sugars.
3. Back at the hive, bees regurgitate and pass it mouth-to-mouth, reducing water content.
4. The thickened honey is sealed into hexagonal wax cells with a cap of beeswax.

### The Waggle Dance
Forager bees communicate food locations through a 'waggle dance' — a figure-8 pattern whose angle indicates direction relative to the sun and whose duration signals distance. Karl von Frisch won the 1973 Nobel Prize for decoding this language.

### Why Bees Matter
- **Pollination** — bees pollinate about 75% of the world's flowering crops, including apples, almonds, coffee, and cocoa.
- **Biodiversity** — wild plants depend on bee pollination to reproduce.
- **Economic value** — pollination services are worth hundreds of billions of dollars annually.

### Threats
Colony Collapse Disorder, pesticide exposure (especially neonicotinoids), Varroa mites, habitat loss, and climate-driven flowering mismatches have caused sharp population declines since the 2000s.

**Why it matters:** Without bees, global food systems would collapse and countless wild plants would vanish. Protecting bees is protecting the foundation of terrestrial ecosystems — and ultimately the food on our own plates.`,
  },

  // ----------------------------------------------------------
  // 3. SHARKS
  // ----------------------------------------------------------
  {
    id: 'sharks',
    patterns: [/\b(sharks|shark|great white shark|mangar|samundar ka machli|shark hunting|shark species|mako shark|hammerhead)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Sharks — Ancient Predators of the Deep

Sharks have patrolled Earth's oceans for over 400 million years — older than dinosaurs, older than trees. They survived all five mass extinctions and today occupy nearly every marine habitat, from coral reefs to the open abyss.

### Major Shark Groups
| Group | Example | Trait |
|-------|---------|-------|
| Lamnidae | Great white, mako | Warm-blooded, fast hunters |
| Carcharhinidae | Tiger, bull, reef sharks | Versatile coastal predators |
| Sphyrnidae | Hammerheads | Electroreceptive head shape |
| Rhincodontidae | Whale shark | Largest fish — filter feeder |
| Squalidae | Dogfish | Small, deep-water sharks |

### Hunting Toolkit
- **Ampullae of Lorenzini** — electroreceptors that detect the faint electrical fields of prey hidden under sand.
- **Lateral line** — senses pressure changes and movement in surrounding water.
- **Replaceable teeth** — a great white may use 30,000 teeth in its lifetime, with new rows rotating forward.
- **Nictitating membrane** — a protective eyelid that shields eyes during attack.
- **Smell** — can detect one drop of blood in a million drops of water.

### Ecological Role
As apex predators, sharks regulate populations of mid-level predators, which in turn protects smaller fish and grazer species. This 'top-down' control keeps coral reefs and fisheries balanced. Removal of sharks in areas like the US Atlantic caused collapse of scallop fisheries as rays multiplied unchecked.

### Misunderstood, Not Mindless
Despite the *Jaws* stereotype, sharks rarely attack humans — about 5–10 fatalities worldwide per year. You are statistically more likely to be killed by lightning, a vending machine, or a selfie than by a shark. Most bites are exploratory, not predatory.

### Threats to Sharks
- **Finning** — up to 73 million sharks killed yearly for shark fin soup.
- **Bycatch** — caught accidentally in tuna and swordfish nets.
- **Slow reproduction** — many species take 15+ years to mature and have few young.

**Why it matters:** Sharks are keystone species whose disappearance would unravel marine food webs. Saving them means preserving the ocean's balance — and the livelihoods of hundreds of millions of people who depend on healthy seas.`,
  },

  // ----------------------------------------------------------
  // 4. ELEPHANTS
  // ----------------------------------------------------------
  {
    id: 'elephants',
    patterns: [/\b(elephants|elephant|haathi|hathi|african elephant|asian elephant|elephant intelligence|ivory|tusks)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Elephants — Giants of Intelligence and Memory

Elephants are the largest living land animals and among the most intelligent creatures on Earth. They display grief, joy, cooperation, tool use, and self-recognition — traits once thought uniquely human.

### Two Main Species
- **African bush elephant** — largest, up to 6 tonnes; big ears shaped like the African continent.
- **African forest elephant** — smaller, darker, lives in dense rainforests.
- **Asian elephant** — smaller ears, only males typically have tusks; culturally important across South and Southeast Asia.

### Brain and Intelligence
An elephant's brain weighs about 5 kg — the largest of any land mammal. It has the same number of neurons as a human brain, with an exceptionally large hippocampus. Elephants:
- **Recognize themselves in mirrors** — the Gallup test of self-awareness.
- **Mourn their dead** — returning to bones of deceased relatives, touching them with trunks.
- **Use tools** — branches to swat flies, modified sticks to scratch.
- **Remember water sources** across decades of drought.
- **Hold 'meetings'** — greeting ceremonies with elaborate rumbling and trumpeting.

### Social Structure
Elephants live in **matriarchal herds** led by the oldest, wisest female. The herd consists of her daughters and their calves. Males leave at puberty (around 12–15 years) and live solitary or in bachelor groups. The matriarch's memory of migration routes, water holes, and danger zones is critical to herd survival.

### Communication
Elephants use infrasound — low-frequency rumbles below human hearing — that can travel up to 10 km through the ground. They also signal with ear flaps, trunk gestures, and seismic vibrations detected through their feet.

### Threats
- **Poaching for ivory** — tens of thousands killed yearly; populations fell from millions to about 415,000 African elephants today.
- **Habitat loss** — farms, roads, and fences fragment migration routes.
- **Human-elephant conflict** — crop raids lead to retaliatory killings.

**Why it matters:** Elephants are ecosystem engineers — they dig water holes, disperse seeds over vast distances, and clear pathways that other animals use. Their disappearance would reshape African and Asian landscapes. Protecting elephants means protecting entire ecosystems and a window into the minds of non-human beings.`,
  },

  // ----------------------------------------------------------
  // 5. DOLPHINS
  // ----------------------------------------------------------
  {
    id: 'dolphins',
    patterns: [/\b(dolphins|dolphin|samundar ka janwar|porpoise|bottlenose dolphin|dolphin intelligence|dolphin communication)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Dolphins — Minds of the Ocean

Dolphins are aquatic mammals — not fish — belonging to the order Cetacea, alongside whales and porpoises. There are about 40 living species, ranging from the 1.5 m Maui's dolphin to the 9 m orca (technically the largest dolphin).

### Anatomy and Adaptations
- **Blowhole** on top of the head for breathing at the surface.
- **Echolocation** — they emit clicks and read the returning echoes to 'see' through murky water with stunning precision, detecting a coin from meters away.
- **Streamlined body** with smooth, hairless skin that reduces drag.
- **Countershading** — dark on top, light below — for camouflage.
- **Half-brain sleep** — one hemisphere rests while the other keeps them breathing and alert for predators.

### Intelligence
Dolphins have brains larger than humans relative to body size, with deeply folded cortices. Documented behaviors include:
- **Signature whistles** — each dolphin invents a unique name-sound and calls others by theirs.
- **Tool use** — bottlenose dolphins in Shark Bay, Australia, wear marine sponges on their beaks to protect them while foraging on the seafloor.
- **Cooperative hunting** — mud-ring feeding in Florida: one dolphin kicks up a ring of mud, fish flee, others wait to catch them.
- **Cultural traditions** — techniques pass from mother to calf across generations.
- **Self-recognition** in mirrors.

### Social Life
Dolphins live in **pods** of a dozen to thousands. Bonds can last decades. They assist injured pod members, mourn dead calves, and even help humans — there are documented cases of dolphins protecting swimmers from sharks by circling them.

### Major Species
| Species | Habitat | Trait |
|---------|---------|-------|
| Bottlenose | Worldwide coastal | Most studied, intelligent |
| Orca (killer whale) | All oceans | Apex predator, matriarchal pods |
| Spinner | Tropical open ocean | Acrobatic leaps and spins |
| Amazon river dolphin | South American rivers | Pink skin, flexible neck |
| Ganges river dolphin | South Asia | Nearly blind, uses echolocation |

### Threats
Bycatch, pollution, noise from shipping and sonar that disrupts echolocation, captivity stress, and climate-driven prey shifts.

**Why it matters:** Dolphins reveal that intelligence evolved independently in the sea — they are not just charming animals but cognitive peers with cultures of their own. Studying them stretches our understanding of mind, consciousness, and what we owe other sentient beings.`,
  },

  // ----------------------------------------------------------
  // 6. LIONS
  // ----------------------------------------------------------
  {
    id: 'lions',
    patterns: [/\b(lions|lion|sher|babbar sher|shah of jangal|king of the jungle|pride|lion hunting|asian lion|african lion)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Lions — The Social Kings of the Savanna

The lion (*Panthera leo*) is the only truly social big cat, living in cooperative groups called prides. Once roaming across Africa, the Middle East, and Asia, lions today survive in scattered pockets of sub-Saharan Africa and a single forest in India.

### Pride Structure
A typical pride has:
- **1–3 adult males** — usually brothers or cousins who took over the pride together.
- **5–15 related females** — the core of the pride, often mothers, daughters, and sisters.
- **Cubs** — born synchronously so females can cross-nurse.

Females do most of the hunting, raising, and territory defense. Males defend the pride against rival males — and a takeover usually means infanticide of the previous cubs, which brings females back into estrus.

### Hunting Strategy
Lions are ambush predators, not endurance runners. They hunt cooperatively:
1. Some females stalk from behind, hiding in tall grass.
2. Others circle to drive prey toward the ambushers.
3. The kill is made by suffocation — clamping jaws over the muzzle of large prey like buffalo, or biting the throat of smaller antelope.

Favored prey includes wildebeest, zebra, buffalo, and warthog. A male can eat 30 kg of meat in a single sitting.

### Habitat
- **African lion** — savanna, scrubland, and dry forest across sub-Saharan Africa. Major populations in Tanzania's Serengeti, Kenya's Masai Mara, and South Africa's Kruger.
- **Asiatic lion** — only about 670 survive in Gir National Park, Gujarat, India. They live in smaller prides and prefer dry deciduous forest.

### The Lion's Roar
A male's roar can be heard up to 8 km away. It advertises territory, locates pride members, and warns rival males. The hyoid bone in the throat is partially cartilaginous, allowing the deep, resonant call.

### Threats and Conservation
- **Population crash** — from perhaps 200,000 a century ago to about 23,000 today.
- **Habitat loss and fragmentation** — farms and fences block migration.
- **Retaliatory killings** — lions that prey on cattle are poisoned.
- **Trophy hunting** — controversial; revenue vs. population impact heavily debated.

**Why it matters:** Lions are apex predators that regulate herbivore populations and shape entire savanna ecosystems. Culturally, they symbolize courage from the Lion of Judah to Asoka's pillar — and their loss would erase a piece of the human imagination along with a keystone of African ecology.`,
  },

  // ----------------------------------------------------------
  // 7. CLIMATE CHANGE
  // ----------------------------------------------------------
  {
    id: 'climate-change',
    patterns: [/\b(climate change|mosam ka tabdeeli|global warming|greenhouse effect|greenhouse gases|carbon emissions|mausam badal|garmi barh rahi)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Climate Change — The Defining Environmental Crisis

Climate change refers to long-term shifts in global temperatures and weather patterns, driven primarily by human activities since the Industrial Revolution. Earth has warmed about 1.2°C above pre-industrial levels — and the rate is accelerating.

### Causes
The root cause is the **enhanced greenhouse effect**:
- Burning **fossil fuels** (coal, oil, gas) releases CO₂ that traps heat.
- **Deforestation** removes the trees that absorb CO₂.
- **Agriculture and livestock** release methane (CH₄) — 80× more warming than CO₂ over 20 years.
- **Cement production** and industrial processes add more CO₂ and nitrous oxide.

Key greenhouse gases:
| Gas | Source | Warming Potential |
|-----|--------|-------------------|
| Carbon dioxide (CO₂) | Fossil fuels, deforestation | Baseline |
| Methane (CH₄) | Cattle, rice paddies, landfills | ~80× over 20 yrs |
| Nitrous oxide (N₂O) | Fertilizers, industry | ~270× |
| Fluorinated gases | Refrigerants, industry | Thousands × |

### Effects
- **Rising seas** — glaciers and polar ice melt; coastal cities like Mumbai, Miami, and Dhaka face flooding.
- **Extreme weather** — stronger hurricanes, longer droughts, deadlier heatwaves.
- **Ecosystem disruption** — coral bleaching, shifting migration patterns, species extinction.
- **Food and water insecurity** — crop yields fall in tropical regions.
- **Climate refugees** — projected to reach hundreds of millions by 2050.

### Solutions
1. **Cut emissions** — transition to solar, wind, hydro, and nuclear power.
2. **Electrify everything** — replace gas cars and heating with electric alternatives.
3. **Protect and restore forests** — especially the Amazon, Congo, and Indonesian rainforests.
4. **Regenerative agriculture** — cover crops, reduced tillage, less synthetic fertilizer.
5. **Carbon pricing** — tax or cap emissions to reflect their true cost.
6. **Adaptation** — seawalls, drought-resistant crops, early-warning systems.

The **Paris Agreement** (2015) aims to keep warming below 1.5°C, but current pledges put the world on track for ~2.7°C.

**Why it matters:** Climate change is not a future threat — it is a present reality reshaping every region, every economy, and every ecosystem. Acting now is far cheaper than paying for inaction, and the window for keeping warming below catastrophic thresholds is rapidly closing.`,
  },

  // ----------------------------------------------------------
  // 8. DEFORESTATION
  // ----------------------------------------------------------
  {
    id: 'deforestation',
    patterns: [/\b(deforestation|jungal katna|jungal ki katraee|jalaao|forest loss|jungle cutting|reforestation|afforestation|jungle bachao)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Deforestation — Clearing the Lungs of the Earth

Deforestation is the large-scale removal of forests, usually for agriculture, logging, or infrastructure. Earth has lost about one-third of its forest cover since the last ice age — and the pace has accelerated sharply since 1950. An area of forest the size of a football pitch is destroyed every second.

### Major Causes
- **Commercial agriculture** — soy, palm oil, cattle ranching; the leading driver in the Amazon and Southeast Asia.
- **Logging** — both legal and illegal, for timber and paper.
- **Subsistence farming** — poor farmers clearing land for food.
- **Infrastructure** — roads, dams, mines, and urban expansion.
- **Fire** — both natural wildfires and deliberate slash-and-burn.

### Hotspots
- **Amazon rainforest** — Brazil, Peru, Colombia; about 17% lost already.
- **Indonesia and Malaysia** — palm oil plantations replacing rainforest.
- **Congo Basin** — second-largest rainforest, threatened by mining and logging.
- **Boreal forests** — Russia and Canada; losses from logging and fire.

### Environmental Impact
- **Carbon release** — burning and decaying trees emit roughly 4.8 billion tonnes of CO₂ per year, ~10% of human emissions.
- **Biodiversity loss** — forests hold about 80% of land species; many vanish with their habitat.
- **Water cycle disruption** — fewer trees means less evapotranspiration, less rainfall, more drought.
- **Soil erosion** — tree roots no longer hold topsoil; rivers silt up and farmland degrades.
- **Indigenous displacement** — communities who have lived in forests for millennia lose their land and culture.

### Reforestation and Restoration
Reforestation replants trees on cleared land; afforestation plants new forests where none recently grew. Successful efforts include:
- **China's Grain for Green** program — converted 28 million hectares of farmland back to forest.
- **Costa Rica** — reversed deforestation to double forest cover, paid for by a carbon tax.
- **The Great Green Wall** — African initiative to restore 100 million hectares across the Sahel.

Tree planting alone cannot offset fossil-fuel emissions — protecting existing, mature forests matters far more than new plantations, since old-growth forests store vastly more carbon.

**Why it matters:** Forests are Earth's climate regulator, water tower, and biodiversity vault. Losing them accelerates warming, dries continents, and erases species we may never discover. Deforestation is reversible if we choose policy, markets, and diets that value standing forests more than cleared land.`,
  },

  // ----------------------------------------------------------
  // 9. CORAL REEFS
  // ----------------------------------------------------------
  {
    id: 'coral-reefs',
    patterns: [/\b(coral reef|coral reefs|munti|marjaan|reef|great barrier reef|coral bleaching|coral polyps)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Coral Reefs — Rainforests of the Sea

Coral reefs are underwater structures built by tiny animals called **polyps**, which secrete calcium carbonate skeletons. Though they cover less than 1% of the ocean floor, reefs support about 25% of all marine species — earning them the nickname 'rainforests of the sea'.

### How Reefs Form
Each coral polyp is a soft animal related to jellyfish, typically just a few millimeters across. It lives in symbiosis with **zooxanthellae** — algae that live inside its tissues, photosynthesize, and provide up to 90% of the polyp's food. In return, the polyp gives the algae shelter and nutrients. Over thousands of years, the accumulated skeletons of countless polyp generations build massive reef structures.

### Major Reefs
| Reef | Location | Feature |
|------|----------|---------|
| Great Barrier Reef | Australia | Largest, ~2,300 km long |
| Mesoamerican Reef | Caribbean | Longest in Atlantic |
| Coral Triangle | SE Asia | Most biodiverse |
| Red Sea Coral Reef | Middle East | Heat-tolerant corals |
| New Caledonia Barrier | Pacific | Second-longest double barrier |

### Biodiversity
A single reef may host thousands of species — fish, sharks, sea turtles, octopuses, sponges, mollusks, and microorganisms. Reefs are nurseries for many open-ocean fish, supporting commercial fisheries worth tens of billions of dollars and feeding hundreds of millions of people.

### Threats
- **Coral bleaching** — when water gets too warm, polyps expel their algae and turn white. Without the algae, they starve. If temperatures remain high, the reef dies. The Great Barrier Reef has suffered mass bleaching events in 2016, 2017, 2020, 2022, and 2024.
- **Ocean acidification** — extra CO₂ dissolves into seawater, forming carbonic acid and dissolving coral skeletons.
- **Overfishing** — removing grazing fish lets algae smother coral.
- **Pollution** — fertilizer runoff feeds crown-of-thorns starfish outbreaks.
- **Physical damage** — anchors, dynamite fishing, and tourist contact.

### Protection
Marine protected areas, sustainable fishing, sewage treatment, coral farming and restoration, and global emissions cuts are all essential. Some 'super corals' show natural heat tolerance and may seed restored reefs.

**Why it matters:** Reefs protect coastlines from storms, feed millions, and harbor compounds used in medicines from painkillers to cancer therapies. Losing them would impoverish the ocean, the climate, and humanity within a single human lifetime.`,
  },

  // ----------------------------------------------------------
  // 10. VOLCANOES
  // ----------------------------------------------------------
  {
    id: 'volcanoes',
    patterns: [/\b(volcano|volcanoes|jwalamukhi|jvalamukhi|eruption|lava|magma|volcanic|mount vesuvius|mount etna|krakatoa)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Volcanoes — Earth's Fiery Pressure Valves

A volcano is a rupture in Earth's crust through which molten rock (magma), gases, and ash escape from the mantle below. Volcanoes are the planet's way of releasing internal heat — and they have shaped the atmosphere, oceans, and continents for billions of years.

### How Volcanoes Form
Magma forms in the mantle where intense heat melts rock. Being lighter than solid rock, magma rises and pools in magma chambers. When pressure builds beyond what the overlying crust can hold, an eruption follows. Most volcanoes sit along **tectonic plate boundaries**, especially the Pacific **Ring of Fire**, which hosts about 75% of the world's active volcanoes.

### Types of Volcanoes
| Type | Profile | Example |
|------|---------|---------|
| Shield | Broad, gentle slopes | Mauna Loa, Hawaii |
| Stratovolcano (composite) | Tall, steep, explosive | Mount Fuji, Vesuvius |
| Cinder cone | Small, steep, short-lived | Parícutin, Mexico |
| Caldera | Huge collapsed crater | Yellowstone |
| Fissure | Long cracks, lava floods | Laki, Iceland |

### Eruption Styles
- **Effusive** — gentle lava flows, as in Hawaii; people can usually evacuate.
- **Explosive** — violent blasts of ash, gas, and pumice; can be deadly.
- **Plinian** — towering ash columns reaching the stratosphere, like Vesuvius in AD 79 that buried Pompeii.

### Famous Eruptions
- **Vesuvius (AD 79)** — buried Pompeii and Herculaneum; about 2,000 dead.
- **Krakatoa (1883)** — loudest sound in recorded history; heard 4,800 km away; 36,000+ dead from tsunamis.
- **Mount St. Helens (1980)** — lateral blast flattened 600 km² of forest.
- **Tambora (1815)** — caused the 'Year Without a Summer'; global crop failures and famine.
- **Eyjafjallajökull (2010)** — ash cloud shut European airspace for weeks.

### Benefits of Volcanoes
- **Fertile soil** — volcanic ash weathers into rich farmland (Indonesia, Italy).
- **Geothermal energy** — Iceland heats homes and generates electricity from volcanic heat.
- **Atmospheric gases** — early volcanoes probably created Earth's first oceans and atmosphere.
- **New land** — Hawaii and Iceland are still growing.

### Hazards
Lava flows, pyroclastic flows (superheated gas and ash racing downhill at 700 km/h), lahars (volcanic mudflows), ash fall, tsunamis, and climate-cooling sulfate aerosols.

**Why it matters:** Volcanoes are reminders that Earth is alive beneath our feet — they create land, enrich soil, and shape climate, but can also devastate entire regions. Studying them helps us farm their fertility, harness their energy, and protect the millions who live within reach of their fire.`,
  },

  // ----------------------------------------------------------
  // 11. EARTHQUAKES
  // ----------------------------------------------------------
  {
    id: 'earthquakes',
    patterns: [/\b(earthquake|earthquakes|zalzala|zilzila|zalzale|tremor|seismic|richter scale|seismograph|fault line)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Earthquakes — When the Ground Shakes

An earthquake is a sudden release of energy in Earth's crust that creates seismic waves. Most are too small to feel, but large ones can topple cities, trigger tsunamis, and reshape coastlines in seconds.

### Causes
- **Tectonic plate movement** — the dominant cause. Earth's crust is divided into about 15 major plates that slowly drift. Where they meet, stress builds until rock suddenly slips along a **fault**, releasing enormous energy.
- **Volcanic activity** — magma movement can fracture surrounding rock.
- **Human-induced** — large dams, fracking, geothermal drilling, and wastewater injection have all caused measurable quakes.

### Measuring Earthquakes
- **Richter scale** — older, logarithmic measure of magnitude (energy released). Each whole number is 10× ground motion and ~32× energy.
- **Moment Magnitude Scale (Mw)** — modern standard, used for major quakes.
- **Modified Mercalli Intensity** — describes felt effects from I (not felt) to XII (total destruction).

| Magnitude | Effect | Frequency/yr |
|-----------|--------|---------------|
| < 2.0 | Micro, not felt | Millions |
| 4.0–4.9 | Light, objects shake | ~10,000 |
| 6.0–6.9 | Damaging in populated areas | ~150 |
| 7.0–7.9 | Major | ~15 |
| 8.0+ | Great, catastrophic | ~1 |

### Major Fault Zones
- **Pacific Ring of Fire** — accounts for ~90% of earthquakes.
- **San Andreas Fault** (California) — North American vs. Pacific plates.
- **North Anatolian Fault** (Turkey).
- **Himalayan front** — India colliding into Asia; responsible for major South Asian quakes.

### Safety During an Earthquake
1. **Drop, Cover, Hold on** — get under a sturdy desk; protect head and neck.
2. **Stay indoors** during shaking — most injuries happen fleeing.
3. **If outside** — move to open ground, away from buildings, power lines, and trees.
4. **If near coast** — after shaking stops, move to high ground immediately; tsunamis can arrive within minutes.
5. **Prepare a kit** — water, food, first aid, flashlight, radio.

### Historic Devastation
- **1556 Shaanxi (China)** — deadliest known, ~830,000 dead.
- **1960 Valdivia (Chile)** — strongest ever recorded, Mw 9.5.
- **2004 Indian Ocean** — Mw 9.1, tsunami killed ~230,000 across 14 countries.
- **2011 Tōhoku (Japan)** — Mw 9.0, tsunami triggered Fukushima disaster.

**Why it matters:** Earthquakes strike without warning and can kill more people in seconds than years of war. Understanding them — and investing in resilient buildings, early warning systems like Japan's, and community drills — is the difference between disaster and survival for hundreds of millions living on active faults.`,
  },

  // ----------------------------------------------------------
  // 12. WATER CYCLE
  // ----------------------------------------------------------
  {
    id: 'water-cycle',
    patterns: [/\b(water cycle|paani ka chakra|pani ka chakra|hydrologic cycle|evaporation|condensation|precipitation|barish|baarish|hydrology)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## The Water Cycle — Earth's Endless Circulation

The water cycle (hydrologic cycle) describes the continuous movement of water between the atmosphere, land, and oceans. Powered by the Sun and gravity, it has operated for billions of years — the same water you drink today may have once flowed through a dinosaur.

### The Main Stages

1. **Evaporation** — the Sun heats oceans, lakes, and rivers, turning liquid water into vapor. About 90% of atmospheric water comes from the oceans.
2. **Transpiration** — plants release water vapor from their leaves; the Amazon effectively 'flies' rivers of moisture downwind.
3. **Condensation** — rising vapor cools and forms tiny droplets around dust, creating clouds and fog.
4. **Precipitation** — droplets combine until heavy enough to fall as rain, snow, sleet, or hail.
5. **Runoff** — water flows over land into streams, rivers, and eventually the sea.
6. **Infiltration** — some water soaks into the ground, recharging aquifers that store 97% of the world's liquid freshwater.
7. **Sublimation** — ice and snow can turn directly into vapor, skipping the liquid phase.

### Quantities
- Earth holds about **1.386 billion km³** of water.
- Only **2.5%** is freshwater — of that, **69%** is locked in glaciers, **30%** in groundwater, and just **0.3%** in rivers and lakes.
- The average water molecule spends 3,200 years in the ocean but only 9 days in the atmosphere.

### Why the Cycle Matters
- **Sustains life** — every organism depends on fresh water.
- **Drives weather** — evaporation fuels hurricanes, monsoons, and storms.
- **Shapes landscapes** — rivers carve canyons, glaciers grind valleys.
- **Recharges aquifers** — many regions, including Pakistan's Indus Basin, depend on groundwater that recharges slowly over centuries.
- **Regulates climate** — water vapor is the most abundant greenhouse gas, and ocean currents redistribute heat around the planet.

### Human Disruption
- **Over-extraction of groundwater** — many aquifers are being drained faster than they refill.
- **Deforestation** — reduces transpiration and downwind rainfall.
- **Climate change** — intensifies the cycle: heavier downpours, longer droughts, faster evaporation.
- **Pollution** — contaminates the freshwater portion that humans can actually use.

**Why it matters:** The water cycle is the bloodstream of the planet. Understanding it teaches us why deforestation causes droughts, why groundwater is finite, and why every drop of freshwater is precious. Tampering with the cycle — through pollution, overuse, or climate change — threatens the foundation of human civilization itself.`,
  },

  // ----------------------------------------------------------
  // 13. CARBON CYCLE
  // ----------------------------------------------------------
  {
    id: 'carbon-cycle',
    patterns: [/\b(carbon cycle|kaarbon chakra|photosynthesis|respiration|fossil fuels|carbon sink|carbon flux|co2 cycle)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## The Carbon Cycle — Earth's Breath of Life

Carbon is the backbone of all life — every protein, fat, sugar, and DNA molecule is built around it. The carbon cycle describes how carbon moves between the atmosphere, oceans, land, and living things, balancing the planet's climate over geological time.

### Major Carbon Reservoirs
| Reservoir | Carbon (billions of tonnes) |
|-----------|------------------------------|
| Oceans | ~38,000 |
| Fossil fuels (underground) | ~5,000–10,000 |
| Soils | ~1,500 |
| Atmosphere | ~870 (rising ~5/yr) |
| Land plants | ~550 |

### Key Processes

1. **Photosynthesis** — plants, algae, and cyanobacteria absorb atmospheric CO₂ and use sunlight to build sugars, releasing oxygen. This is how carbon enters the living world.

2. **Respiration** — plants, animals, and microbes break down sugars for energy, releasing CO₂ back into the air.

3. **Decomposition** — when organisms die, decomposers return their carbon to soil and atmosphere. Some buried organic matter, over millions of years of heat and pressure, becomes **coal, oil, and natural gas** — fossil fuels.

4. **Ocean exchange** — oceans absorb about a quarter of human CO₂ emissions, forming carbonic acid. Marine organisms build shells of calcium carbonate that over geological time become limestone — Earth's largest long-term carbon sink.

5. **Combustion** — burning biomass or fossil fuels rapidly oxidizes carbon back to CO₂.

### The Human Disruption
For most of human history, the cycle was roughly balanced — natural fluxes in and out of the atmosphere were similar. But since 1850:
- Burning fossil fuels has moved **hundreds of billions of tonnes** of buried carbon into the atmosphere in just over a century.
- Deforestation has reduced the land's ability to absorb CO₂.
- Atmospheric CO₂ has risen from **280 ppm to over 420 ppm** — the highest in at least 3 million years.

The oceans have absorbed about 30% of this extra CO₂, causing **ocean acidification** that harms corals and shellfish.

### Carbon Sinks and Sources
- **Sinks** (absorb carbon): forests, oceans, soils, wetlands, peatlands.
- **Sources** (release carbon): fossil fuel burning, deforestation, permafrost thaw, intensive agriculture.

**Why it matters:** The carbon cycle is the climate's thermostat. By unearthing fossil carbon far faster than nature can re-bury it, humans are resetting that thermostat — warming the planet, acidifying oceans, and destabilizing ecosystems that took millions of years to form. Restoring balance means both cutting emissions and protecting the natural sinks that still keep Earth habitable.`,
  },

  // ----------------------------------------------------------
  // 14. ENDANGERED SPECIES
  // ----------------------------------------------------------
  {
    id: 'endangered-species',
    patterns: [/\b(endangered species|khatre mein species|khatara species|extinct|extinction|red list|IUCN|conservation|vulnerable species)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Endangered Species — On the Brink of Extinction

An endangered species is one at serious risk of dying out. Earth is currently undergoing the **Sixth Mass Extinction** — species are disappearing at 100 to 1,000 times the natural background rate, almost entirely due to human activity.

### IUCN Red List Categories
The International Union for Conservation of Nature ranks species by extinction risk:
1. **Least Concern** — widespread and abundant.
2. **Near Threatened** — close to qualifying for a threatened category.
3. **Vulnerable** — high risk of extinction in the wild.
4. **Endangered** — very high risk.
5. **Critically Endangered** — extremely high risk, often fewer than 250 mature individuals.
6. **Extinct in the Wild** — survives only in captivity.
7. **Extinct** — no living individuals remain.

Over 44,000 species are currently threatened with extinction.

### Major Causes
- **Habitat loss** — agriculture, logging, urbanization; the biggest driver.
- **Overexploitation** — hunting, fishing, poaching.
- **Invasive species** — rats and cats have wiped out countless island species.
- **Pollution** — plastics, pesticides, oil spills, agricultural runoff.
- **Climate change** — shifting temperatures faster than species can migrate or adapt.

### Famous Endangered Species
| Species | Status | Main Threat |
|---------|--------|-------------|
| Vaquita | Critically Endangered | Bycatch (gillnets) |
| Sumatran rhino | Critically Endangered | Poaching, habitat loss |
| Amur leopard | Critically Endangered | Poaching, deforestation |
| Mountain gorilla | Endangered | Habitat loss, disease |
| Blue whale | Endangered | Ship strikes, historic whaling |
| Snow leopard | Vulnerable | Poaching, climate change |
| Hawksbill turtle | Critically Endangered | Egg collection, illegal trade |

### Conservation Successes
- **Bald eagle** — delisted in 2007 after DDT ban and protection.
- **Giant panda** — downlisted from Endangered to Vulnerable in 2016.
- **Humpback whale** — recovered from a few thousand to over 80,000 after the whaling moratorium.
- **Arabian oryx** — bred in captivity and reintroduced; first species to move from 'Extinct in the Wild' to 'Vulnerable'.

### Conservation Approaches
- **Protected areas** — national parks, marine reserves.
- **Captive breeding** — zoos and aquariums breed species for reintroduction.
- **Anti-poaching patrols** and wildlife laws (CITES).
- **Community conservation** — local people benefit from protecting wildlife.

**Why it matters:** Every species is a unique outcome of millions of years of evolution — once gone, it cannot be replaced. Biodiversity underpins food security, medicine, clean water, and climate stability. Losing species weakens the web of life that supports humanity itself, and the disappearance of one organism can trigger cascading losses across entire ecosystems.`,
  },

  // ----------------------------------------------------------
  // 15. RAINFORESTS
  // ----------------------------------------------------------
  {
    id: 'rainforests',
    patterns: [/\b(rainforests|rainforest|barish ke jangal|barish ka jangal|tropical forest|amazon rainforest|amazon jungle|tropical rainforest)\b/i],
    intent: 'factual_question',
    topic: 'nature',
    response: () => `## Rainforests — The Most Diverse Ecosystems on Earth

Rainforests are dense, warm, wet forests that receive more than 1,800 mm of rain per year. Though they cover only about 6% of Earth's land surface, they harbor more than half of all terrestrial species — the most biodiverse ecosystems on the planet.

### The Four Layers
Rainforest life is vertically stratified into four layers:

1. **Emergent layer** — giant trees reaching 60–80 m above the canopy, exposed to full sun and wind. Home to eagles, butterflies, and bats.
2. **Canopy** — the dense 'roof' at 30–45 m where most rainforest animals live: monkeys, toucans, sloths, tree frogs, and most insect species.
3. **Understory** — darker, cooler layer of young trees, shrubs, and ferns adapted to low light. Jaguars and many reptiles hunt here.
4. **Forest floor** — rich in decomposing leaves and fungi but poor in nutrients. Only 1–2% of sunlight reaches here. Ants, termites, and tapirs thrive.

### Major Rainforests
| Rainforest | Location | Size |
|------------|----------|------|
| Amazon | South America | ~5.5 million km² |
| Congo Basin | Central Africa | ~2 million km² |
| Daintree | Australia | Oldest continuously surviving |
| Borneo lowland | SE Asia | Extremely biodiverse |
| Tongass | Alaska | Largest temperate rainforest |

### Biodiversity Wonders
- A single Amazonian tree can host more ant species than all of Britain.
- Rainforests contain over 40,000 plant species, 1,300 bird species, and 3,000 fish species.
- Medicines from rainforest plants include quinine (malaria) and vincristine (leukemia).
- Indigenous peoples have lived sustainably in rainforests for thousands of years.

### Ecosystem Services
- **Carbon storage** — rainforests store billions of tonnes of carbon; the Amazon alone holds about 76 billion tonnes.
- **Climate regulation** — evapotranspiration from the Amazon generates 'flying rivers' that bring rain to farmlands across South America.
- **Water cycle** — they feed major rivers like the Amazon, Congo, and Mekong.
- **Soil protection** — tree roots prevent erosion and landslides.

### Threats
Deforestation for cattle, soy, palm oil, logging, and mining destroys about 10 million hectares per year. The Amazon is approaching a tipping point where it could flip from rainforest to savanna, releasing vast stored carbon.

**Why it matters:** Rainforests are the planet's biological treasure chest and its largest land-based carbon sink. Their loss would trigger mass extinctions, disrupt rainfall across continents, accelerate climate change, and erase the cultures and knowledge of the indigenous peoples who call them home. Protecting rainforests is protecting the future of life on Earth.`,
  },
]
